import ant from "@/utils/antd";
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./model/store";
import Scrollbar from "@/components/common/element/scrollbar/index.js";
import "ant-design-vue/dist/antd.css";
import "@/assets/custom-theme/index.css";
import "@/assets/iconfont/iconfont.css";
const app = createApp(App);
app.use(store);
app.use(router);
app.use(ant);
app.mount("#app");
Scrollbar.install(app);
